// Data access for My Tasks. Full Task objects live in the `data` jsonb column;
// the flat columns exist for relational links / filtering. Mock fallback.

import { supabase } from "@/lib/supabase";
import { TASKS, Task } from "@/lib/data/tasks";
import { BRANDS, BRAND_ORDER, BrandId } from "@/lib/brands";
import { notify } from "@/lib/notify";
import { workLink } from "@/lib/deepLink";
import { assertDbOk } from "@/lib/db/assert";
import { liveOnly, trashReady } from "@/lib/db/trash";

const DEFAULT_DONE = [1, 4, 7, 8, 12, 14, 18, 20];

// Task.brand is a display name ("Teppen"); the flat column needs a brand id.
const brandId = (v: string): BrandId | null => {
  const low = (v || "").toLowerCase();
  if (BRANDS[low as BrandId]) return low as BrandId;
  return BRAND_ORDER.find((id) => BRANDS[id].name.toLowerCase() === low) ?? null;
};

/** All tasks + the set of ids currently marked done. */
export async function fetchTasks(): Promise<{ tasks: Task[]; doneIds: number[] }> {
  const db = supabase();
  if (!db) return { tasks: TASKS.map((t) => ({ ...t })), doneIds: [...DEFAULT_DONE] };
  const { data, error } = await liveOnly(db.from("tasks").select("id, done, campaign_id, data"), await trashReady()).order("id");
  // Never show demo work when a configured production query fails; doing so
  // made dashboards report active tasks that did not exist in the live table.
  if (error || !data) return { tasks: [], doneIds: [] };
  // campaign_id is a real column here, not a key inside the data blob (the
  // blob predates it), so it has to be merged in on read or every consumer
  // sees campaignId as undefined.
  const tasks = data
    .map((r) => {
      const t = r.data as Task;
      if (!t) return null;
      return r.campaign_id ? { ...t, campaignId: r.campaign_id as string } : t;
    })
    .filter(Boolean) as Task[];
  const doneIds = data.filter((r) => r.done || (r.data as Task)?.status === "Done").map((r) => (r.data as Task).id);
  return { tasks, doneIds };
}

/** Insert a newly created task. Fire-and-forget. */
/** Shared revision → My Task helper. Any "Request Revision" across the OS
 *  (content post, graphic deliverable, campaign brief) drops a high-priority
 *  task into the person-to-fix's My Tasks, due in `dueDays` days, so nothing
 *  that needs reworking lives only inside a drawer. */
export async function createRevisionTask(opts: {
  module: "Content" | "Graphic" | "Campaign" | "KOL";
  title: string;
  assignee: string;
  brand: string;
  campaign: string;
  reason: string;
  by: string;
  relatedGraphicId?: string;
  relatedBrief?: string;
  dueDays?: number;
}): Promise<void> {
  const ICON: Record<string, { icon: string; color: string }> = {
    Content: { icon: "📝", color: "#5D9E35" },
    Graphic: { icon: "🎨", color: "#C2691E" },
    Campaign: { icon: "🎯", color: "#6C5CE7" },
    KOL: { icon: "🤝", color: "#B5577E" },
  };
  const meta = ICON[opts.module];
  const due = new Date(); due.setDate(due.getDate() + (opts.dueDays ?? 2));
  const task: Task = {
    id: Date.now() + Math.floor(Math.random() * 1000),
    title: opts.title,
    module: opts.module, moduleIcon: meta.icon, moduleColor: meta.color, type: opts.module,
    assignee: opts.assignee, brand: opts.brand, campaign: opts.campaign,
    status: "Todo", priority: "High", group: "doFirst",
    due: due.toLocaleDateString("en-GB", { day: "numeric", month: "short" }),
    dueIso: due.toISOString().slice(0, 10),
    blocker: null, pendingApprover: null, isQuickWin: false,
    nextAction: `แก้ตาม feedback จาก ${opts.by}: ${opts.reason}`,
    checklist: ["อ่าน feedback", "แก้ไขงาน", "ส่งกลับให้ตรวจอีกครั้ง"],
    relatedGraphicId: opts.relatedGraphicId, relatedBrief: opts.relatedBrief,
  };
  await createTaskDb(task);
}

export async function createTaskDb(t: Task): Promise<void> {
  notify("newTask", `🗒️ งานใหม่: ${t.title}`, `มอบหมายให้ ${t.assignee} · ${t.brand} · due ${t.due}`, workLink.task(t.id), { to: [t.assignee] });
  const db = supabase();
  if (!db) return;
  const { error } = await db.from("tasks").insert({
    title: t.title, brand: brandId(t.brand), campaign: t.campaign, campaign_id: t.campaignId ?? null, assignee: t.assignee,
    type: t.type, priority: t.priority, status: t.status, due: t.due,
    next_action: t.nextAction, blocker: t.blocker, checklist: t.checklist ?? [],
    done: t.status === "Done", data: t,
  });
  assertDbOk(error, "Could not save task");
}

/** Create or update one stable task generated by a Campaign Brief. Editing and
 * resubmitting the brief must refresh its work, not create duplicate rows. */
export async function upsertBriefTask(task: Task, key: string): Promise<{ created: boolean }> {
  const db = supabase();
  const next: Task = { ...task, briefTaskKey: key };
  if (!db) return { created: true };
  const { data, error } = await db.from("tasks").select("id,data").filter("data->>relatedBrief", "eq", task.relatedBrief || "");
  assertDbOk(error, "Could not check existing brief task");
  const rows = data ?? [];
  const existing = rows.find((row) => {
    const current = row.data as Task;
    return current.briefTaskKey === key
      || (!!task.relatedGraphicId && current.relatedGraphicId === task.relatedGraphicId)
      || (!current.briefTaskKey && current.type === task.type && current.title === task.title);
  });
  if (!existing) {
    await createTaskDb(next);
    return { created: true };
  }
  const current = existing.data as Task;
  const merged: Task = {
    ...current,
    ...next,
    // Preserve progress and conversation while refreshing the edited brief.
    status: current.status,
    group: current.group,
    checklistDone: current.checklistDone,
    comments: current.comments,
  };
  const { error: updateError } = await db.from("tasks").update({
    title: merged.title, brand: brandId(merged.brand), campaign: merged.campaign, campaign_id: merged.campaignId ?? null, assignee: merged.assignee,
    type: merged.type, priority: merged.priority, status: merged.status, due: merged.due,
    next_action: merged.nextAction, blocker: merged.blocker, checklist: merged.checklist ?? [],
    done: merged.status === "Done", data: merged,
  }).eq("id", (existing as { id: number }).id);
  assertDbOk(updateError, "Could not update brief task");
  return { created: false };
}

/** Patch an existing task's data blob (matched by its app id). */
export async function updateTaskDb(id: number, patch: Partial<Task>): Promise<void> {
  const db = supabase();
  if (!db) return;
  const { data, error } = await db.from("tasks").select("id, data").eq("data->>id", String(id)).maybeSingle();
  assertDbOk(error, "Could not load task");
  if (!data) throw new Error("Task not found");
  const merged = { ...(data.data as Task), ...patch };
  const row: Record<string, unknown> = { data: merged };
  if (patch.status === "Done") row.done = true;
  if (patch.assignee !== undefined) row.assignee = patch.assignee;
  const { error: updateError } = await db.from("tasks").update(row).eq("id", (data as { id: number }).id);
  assertDbOk(updateError, "Could not update task");
}

export const markDoneDb = (id: number) => updateTaskDb(id, { status: "Done" });
export const reassignDb = (id: number, to: string) => {
  notify("newTask", `🔁 งาน #${id} ถูกส่งต่อให้ ${to}`, undefined, workLink.task(id), { to: [to] });
  return updateTaskDb(id, { assignee: to });
};

/** An id no other task is using.
 *
 *  Task ids have to be unique: updateTaskDb and every deep link find a task by
 *  `data->>id`. The readable `<graphicId><slot>` number is worth keeping when it
 *  works, but it is only a preference — identity is the slot (see
 *  Task.graphicSlot), so anything unused will do.
 *
 *  Two ways the preferred number fails, both live on this database:
 *
 *  1. Taken by another module. Task 246 ("kOL_AUG_LIST") holds 178515553116402,
 *     which is graphic 1785155531164 slot 02.
 *  2. Not exactly representable. Request ids run to 16 digits (1786515010324000,
 *     the OMD_2609_007 series), so `${id}01` is 18 digits — past 2^53, where
 *     doubles are spaced 32 apart. All three slots round to the SAME number, and
 *     the three jobs would fight over one id. Eight live requests are like this.
 *
 *  The generated fallback stays inside the exact range: Date.now() is ~1.79e15,
 *  well under 2^53, where adding the jitter still changes the value. The earlier
 *  `Date.now() * 1000` did not — at 1.79e18 the spacing is 256, so the jitter
 *  vanished and two tasks made in the same millisecond could collide. */
async function freeTaskId(preferred: number): Promise<number> {
  const db = supabase();
  if (!db) return preferred;
  const taken = async (id: number) =>
    !!(await db.from("tasks").select("id").eq("data->>id", String(id)).maybeSingle()).data;
  if (Number.isSafeInteger(preferred) && !(await taken(preferred))) return preferred;
  for (let attempt = 0; attempt < 5; attempt++) {
    const candidate = Date.now() + Math.floor(Math.random() * 1_000_000);
    if (!(await taken(candidate))) return candidate;
  }
  return Date.now() + Math.floor(Math.random() * 1_000_000);
}

/** Create or update ONE My Tasks row for one job of a Graphic request —
 *  storyboard, shoot or artwork. Keyed by the task's deterministic slot id so
 *  re-assigning a shooter updates the shooter's row and leaves the designer's
 *  alone. See graphicAssignmentTasks for which jobs produce a row. */
export async function upsertGraphicTask(task: Task): Promise<void> {
  const db = supabase();
  if (!db || !task.relatedGraphicId || !task.graphicSlot) return;

  // Identity is (relatedGraphicId, graphicSlot) — the request and which of its
  // jobs this is. NOT the numeric id: other modules mint ids from Date.now() in
  // the same range and one already collides with a shoot slot, so an id lookup
  // could return a KOL task and this function would overwrite it.
  //
  // Revision tasks also carry relatedGraphicId, which is why the slot is part
  // of the match and not just a filter on the request.
  const found = await db.from("tasks")
    .select("id, data")
    .eq("data->>relatedGraphicId", String(task.relatedGraphicId))
    .eq("data->>graphicSlot", task.graphicSlot)
    .maybeSingle();
  assertDbOk(found.error, "Could not check existing graphic task");

  // Artwork rows written before slots existed have no graphicSlot to match on,
  // so fall back to the id they were created with. The update below stamps the
  // slot, and they are found the modern way from then on.
  let data = found.data;
  if (!data && task.graphicSlot === "artwork") {
    const legacy = await db.from("tasks").select("id, data").eq("data->>id", String(task.id)).maybeSingle();
    assertDbOk(legacy.error, "Could not check existing graphic task");
    data = legacy.data;
  }

  if (!data) {
    if (task.assignee === "Unassigned") return;
    // A job that is already finished does not need a row inventing for it.
    // Without this, syncing an old request would drop "ถ่ายงาน …" into the
    // shooter's list — already ticked — for a shoot they wrapped weeks ago.
    if (task.status === "Done") return;
    return createTaskDb({ ...task, id: await freeTaskId(task.id) });
  }

  const current = data.data as Task;
  const patch: Partial<Task> = {
    title: task.title,
    // Stamps the slot on rows that predate it, so the id fallback above is
    // needed exactly once per row.
    graphicSlot: task.graphicSlot,
    assignee: task.assignee,
    brand: task.brand,
    campaign: task.campaign,
    due: task.due,
    dueIso: task.dueIso,
    nextAction: task.nextAction,
    pendingApprover: task.pendingApprover,
    status: task.assignee === "Unassigned" ? "Todo" : current.status === "Done" ? current.status : task.status,
    group: task.assignee === "Unassigned" ? "quickWins" : current.status === "Done" ? current.group : task.group,
  };

  if (current.assignee !== task.assignee && task.assignee !== "Unassigned") {
    notify("newTask", `🔁 งานกราฟิกถูกมอบหมายให้ ${task.assignee}`, `${task.title} · ${task.brand}`, task.relatedGraphicId ? workLink.graphic(task.relatedGraphicId) : workLink.task(task.id),
      { team: "graphic", to: [task.assignee] });
  }

  await updateTaskDb(current.id, patch);
}
