// Data access for My Tasks. Full Task objects live in the `data` jsonb column;
// the flat columns exist for relational links / filtering. Mock fallback.

import { supabase } from "@/lib/supabase";
import { TASKS, Task } from "@/lib/data/tasks";
import { BRANDS, BRAND_ORDER, BrandId } from "@/lib/brands";
import { notify } from "@/lib/notify";

const DEFAULT_DONE = [1, 4, 7, 8, 12, 14, 18, 20];

// Task.brand is a display name ("Teppen"); the flat column needs a brand id.
const brandId = (v: string): BrandId | null => {
  const low = (v || "").toLowerCase();
  if (BRANDS[low as BrandId]) return low as BrandId;
  return BRAND_ORDER.find((id) => BRANDS[id].name.toLowerCase() === low) ?? null;
};

/** All tasks + the set of ids currently marked done. */
export async function fetchTasks(): Promise<{ tasks: Task[]; doneIds: number[] }> {
  const db = supabase();
  if (!db) return { tasks: TASKS.map((t) => ({ ...t })), doneIds: [...DEFAULT_DONE] };
  const { data, error } = await db.from("tasks").select("id, done, data").order("id");
  // Never show demo work when a configured production query fails; doing so
  // made dashboards report active tasks that did not exist in the live table.
  if (error || !data) return { tasks: [], doneIds: [] };
  const tasks = data.map((r) => r.data as Task).filter(Boolean);
  const doneIds = data.filter((r) => r.done || (r.data as Task)?.status === "Done").map((r) => (r.data as Task).id);
  return { tasks, doneIds };
}

/** Insert a newly created task. Fire-and-forget. */
export async function createTaskDb(t: Task): Promise<void> {
  notify("newTask", `🗒️ งานใหม่: ${t.title}`, `มอบหมายให้ ${t.assignee} · ${t.brand} · due ${t.due}`, "/my-tasks");
  const db = supabase();
  if (!db) return;
  await db.from("tasks").insert({
    title: t.title, brand: brandId(t.brand), campaign: t.campaign, assignee: t.assignee,
    type: t.type, priority: t.priority, status: t.status, due: t.due,
    next_action: t.nextAction, blocker: t.blocker, checklist: t.checklist ?? [],
    done: t.status === "Done", data: t,
  });
}

/** Create or update one stable task generated by a Campaign Brief. Editing and
 * resubmitting the brief must refresh its work, not create duplicate rows. */
export async function upsertBriefTask(task: Task, key: string): Promise<{ created: boolean }> {
  const db = supabase();
  const next: Task = { ...task, briefTaskKey: key };
  if (!db) return { created: true };
  const { data, error } = await db.from("tasks").select("id,data").filter("data->>relatedBrief", "eq", task.relatedBrief || "");
  if (error) return { created: false };
  const rows = data ?? [];
  const existing = rows.find((row) => {
    const current = row.data as Task;
    return current.briefTaskKey === key
      || (!!task.relatedGraphicId && current.relatedGraphicId === task.relatedGraphicId)
      || (!current.briefTaskKey && current.type === task.type && current.title === task.title);
  });
  if (!existing) {
    await createTaskDb(next);
    return { created: true };
  }
  const current = existing.data as Task;
  const merged: Task = {
    ...current,
    ...next,
    // Preserve progress and conversation while refreshing the edited brief.
    status: current.status,
    group: current.group,
    checklistDone: current.checklistDone,
    comments: current.comments,
  };
  await db.from("tasks").update({
    title: merged.title, brand: brandId(merged.brand), campaign: merged.campaign, assignee: merged.assignee,
    type: merged.type, priority: merged.priority, status: merged.status, due: merged.due,
    next_action: merged.nextAction, blocker: merged.blocker, checklist: merged.checklist ?? [],
    done: merged.status === "Done", data: merged,
  }).eq("id", (existing as { id: number }).id);
  return { created: false };
}

/** Patch an existing task's data blob (matched by its app id). */
export async function updateTaskDb(id: number, patch: Partial<Task>): Promise<void> {
  const db = supabase();
  if (!db) return;
  const { data } = await db.from("tasks").select("id, data").eq("data->>id", String(id)).maybeSingle();
  if (!data) return;
  const merged = { ...(data.data as Task), ...patch };
  const row: Record<string, unknown> = { data: merged };
  if (patch.status === "Done") row.done = true;
  if (patch.assignee !== undefined) row.assignee = patch.assignee;
  await db.from("tasks").update(row).eq("id", (data as { id: number }).id);
}

export const markDoneDb = (id: number) => updateTaskDb(id, { status: "Done" });
export const reassignDb = (id: number, to: string) => {
  notify("newTask", `🔁 งาน #${id} ถูกส่งต่อให้ ${to}`, undefined, "/my-tasks");
  return updateTaskDb(id, { assignee: to });
};

/** Create or update the single My Tasks row that represents a Graphic request
 *  assignment. Keyed by relatedGraphicId so re-assign updates the same task. */
export async function upsertGraphicTask(task: Task): Promise<void> {
  const db = supabase();
  if (!db || !task.relatedGraphicId) return;

  const { data } = await db.from("tasks")
    .select("id, data")
    .eq("data->>relatedGraphicId", String(task.relatedGraphicId))
    .maybeSingle();

  if (!data) {
    if (task.assignee === "Unassigned") return;
    return createTaskDb(task);
  }

  const current = data.data as Task;
  const patch: Partial<Task> = {
    title: task.title,
    assignee: task.assignee,
    brand: task.brand,
    campaign: task.campaign,
    due: task.due,
    dueIso: task.dueIso,
    nextAction: task.nextAction,
    pendingApprover: task.pendingApprover,
    status: task.assignee === "Unassigned" ? "Todo" : current.status === "Done" ? current.status : task.status,
    group: task.assignee === "Unassigned" ? "quickWins" : current.status === "Done" ? current.group : task.group,
  };

  if (current.assignee !== task.assignee && task.assignee !== "Unassigned") {
    notify("newTask", `🔁 งานกราฟิกถูกมอบหมายให้ ${task.assignee}`, `${task.title} · ${task.brand}`, "/my-tasks");
  }

  await updateTaskDb(current.id, patch);
}
