-- ═══════════════════════════════════════════════════════════════════════
-- Marketing OS — Supabase schema (all 12 modules)
-- Run this once in the Supabase SQL editor (Dashboard → SQL → New query).
-- Safe to re-run: every object uses "if not exists" / "drop policy if exists".
--
-- RLS is enabled with DEMO-OPEN policies (anyone with the anon key can read &
-- write) so the app works immediately. Tighten these before a public launch —
-- see the "PRODUCTION" note at the bottom.
-- ═══════════════════════════════════════════════════════════════════════

-- ── Foundation ─────────────────────────────────────────────────────────
create table if not exists brands (
  id            text primary key,          -- teppen | omakase | mainichi | touka
  name          text not null,
  color         text not null,
  lead          text,
  branches      int  default 0,
  campaigns     int  default 0,
  budget        text,
  branch_list   text[] default '{}'
);

-- ── 1. Campaigns ───────────────────────────────────────────────────────
create table if not exists campaigns (
  id              text primary key,        -- CAM-2026-0001
  name            text not null,
  brand           text references brands(id),
  branch          text,
  owner           text,
  budget          numeric default 0,
  spend           numeric default 0,
  roi             numeric default 0,
  dates           text,
  status          text,                    -- Active | Draft | Completed | ...
  camp_type       text,
  readiness       text,
  task_blocked    int default 0,
  task_waiting    int default 0,
  task_overdue    int default 0,
  task_total      int default 0,
  task_done       int default 0,
  task_in_progress int default 0,
  bottleneck_team text,
  next_approval   text,
  created_at      timestamptz default now()
);

-- ── 2. Tasks (My Tasks) ────────────────────────────────────────────────
create table if not exists tasks (
  id           bigint generated by default as identity primary key,
  title        text not null,
  brand        text references brands(id),
  campaign     text,
  campaign_id  text references campaigns(id),   -- relational link
  assignee     text,
  type         text,
  priority     text,
  status       text,
  due          text,
  next_action  text,
  blocker      text,
  checklist    jsonb default '[]',
  done         boolean default false,
  created_at   timestamptz default now()
);

-- ── 3. Content Calendar ────────────────────────────────────────────────
create table if not exists content_posts (
  id           bigint generated by default as identity primary key,
  title        text not null,
  brand        text references brands(id),
  campaign     text,
  campaign_id  text references campaigns(id),
  platforms    text[] default '{}',
  status       text,                        -- Draft | Ready | Approved | ...
  day          int,
  time         text,
  owner        text,
  caption      text,
  asset        text,
  created_at   timestamptz default now()
);

-- ── 4. Graphic Requests ────────────────────────────────────────────────
create table if not exists graphic_requests (
  id            bigint generated by default as identity primary key,
  title         text not null,
  brand         text references brands(id),
  campaign      text,
  campaign_id   text references campaigns(id),
  designer      text,
  requester     text,
  approver      text,
  type          text,
  priority      text,
  stage         text,
  due           text,
  platform      text,
  size          text,
  brief_complete boolean default false,
  blocker       text,
  next_action   text,
  created_at    timestamptz default now()
);

-- ── 5. KOL / Creator ───────────────────────────────────────────────────
create table if not exists kols (
  id           bigint generated by default as identity primary key,
  name         text not null,
  handle       text,
  brand        text references brands(id),
  campaign     text,
  tier         text,
  platform     text,
  followers    numeric,
  rate         numeric,
  status       text,
  stage        text,
  owner        text,
  created_at   timestamptz default now()
);

-- ── 6. Finance ─────────────────────────────────────────────────────────
create table if not exists budget_items (
  id           bigint generated by default as identity primary key,
  section_key  text,
  section_label text,
  name         text,
  budget       numeric default 0,
  actual       numeric default 0
);
create table if not exists expenses (
  id           bigint generated by default as identity primary key,
  vendor       text,
  category     text,
  brand        text references brands(id),
  amount       numeric default 0,
  vat          numeric default 0,
  date         text,
  status       text
);
create table if not exists expense_requests (
  id           bigint generated by default as identity primary key,
  category     text,
  brand        text references brands(id),
  campaign     text,
  requested    numeric default 0,
  approved     numeric default 0,
  due          text,
  status       text
);
create table if not exists pnl (
  id           bigint generated by default as identity primary key,
  name         text,
  brand        text references brands(id),
  revenue      numeric default 0,
  budget       numeric default 0,
  expense      numeric default 0,
  roi          numeric default 0,
  roas         numeric default 0
);

-- ── 7. Request Center / 8. Approval Queue (shared) ─────────────────────
create table if not exists requests (
  id           text primary key,           -- REQ-0001
  type         text,
  type_icon    text,
  title        text not null,
  brand        text references brands(id),
  campaign     text,
  campaign_id  text references campaigns(id),
  requester    text,
  approver     text,
  due          text,
  stage        text,
  priority     text,
  created_at   timestamptz default now()
);

-- ── 9. Asset Library ───────────────────────────────────────────────────
create table if not exists assets (
  id           bigint generated by default as identity primary key,
  name         text not null,
  type         text,
  brand        text references brands(id),
  campaign     text,
  version      text,
  approval     text,
  updated      text,
  drive_url    text,
  canva_url    text
);

-- ── 10. Team Workload ──────────────────────────────────────────────────
create table if not exists workload_members (
  id           bigint generated by default as identity primary key,
  name         text not null,
  role         text,
  team         text,
  color        text,
  capacity     int default 0,
  assigned     int default 0,
  status       text
);

-- ── 11. Settings ───────────────────────────────────────────────────────
create table if not exists members (
  email        text primary key,
  name         text not null,
  role         text,
  access       text,                        -- Admin | Editor | Viewer
  brand_access text,
  status       text default 'Active',
  color        text
);
create table if not exists permissions (
  role         text primary key,
  descr        text,
  perms        jsonb default '[]'           -- level per module
);
create table if not exists org_settings (
  key          text primary key,
  label        text,
  value        text
);

-- ── 12. Work Calendar (Work Flow) ──────────────────────────────────────
create table if not exists workflow_tasks (
  id           bigint generated by default as identity primary key,
  section_key  text,
  en           text not null,
  jp           text,
  responsible  text,
  accountable  text,
  link         text,
  note         text,
  qty          text,
  marks        jsonb default '{}'           -- { "1": "7", "8": "9", ... }
);

-- ── External: Agency Portal ────────────────────────────────────────────
create table if not exists agency_tasks (
  id           bigint generated by default as identity primary key,
  title        text not null,
  brand        text references brands(id),
  campaign     text,
  campaign_id  text references campaigns(id),
  type         text,
  status       text,
  due          text,
  brief        text,
  link         text,
  note         text,
  created_at   timestamptz default now()
);

-- ── Campaign Submodule: Promotion Summary Print ───────────────────────
create table if not exists promotion_summary_items (
  id          text primary key,
  brand       text references brands(id),
  category    text not null,
  title       text not null,
  description text not null default '',
  pos_name    text,
  branches    text[] default '{}',
  start_date  text not null,
  end_date    text,
  status      text not null default 'active',
  source      text not null default 'manual',
  created_at  timestamptz default now(),
  updated_at  timestamptz default now()
);

-- ═══════════════════════════════════════════════════════════════════════
-- RLS — demo-open policies (enable RLS, then allow all with the anon key)
-- ═══════════════════════════════════════════════════════════════════════
do $$
declare t text;
begin
  foreach t in array array[
    'brands','campaigns','tasks','content_posts','graphic_requests','kols',
    'budget_items','expenses','expense_requests','pnl','requests','assets',
    'workload_members','members','permissions','org_settings','workflow_tasks',
    'agency_tasks','promotion_summary_items'
  ] loop
    execute format('alter table %I enable row level security;', t);
    execute format('drop policy if exists demo_all on %I;', t);
    execute format('create policy demo_all on %I for all using (true) with check (true);', t);
  end loop;
end $$;

-- ═══════════════════════════════════════════════════════════════════════
-- PRODUCTION: replace each demo_all policy with role-aware rules, e.g.
--   create policy read_all   on tasks for select using (auth.role() = 'authenticated');
--   create policy write_own  on tasks for insert with check (auth.uid() = created_by);
-- and add an `agency` role that can only see/edit agency_tasks (external portal).
-- ═══════════════════════════════════════════════════════════════════════
